name: Label Issues (Script Injection)
on:
  issues:
    types:
      - opened

jobs:
  assign-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add a Label
        env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          issue_title="${{ github.event.issue.title }}"
          if [[ "$issue_title" == *"bug"* ]]; then
            echo "Issue is about a bug"
            echo "Assigning label - BUG ....  ............. ......"
          else
            echo "Not a bug"
          fi
